# Generated by Django 3.2.9 on 2021-11-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя актёра')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя Писателя')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('imdb_rating', models.CharField(max_length=255, verbose_name='Рейтинг фильмов')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанры')),
                ('description', models.CharField(max_length=255, verbose_name='Описание фильма')),
                ('writers_names', models.CharField(max_length=255, null=True, verbose_name='Список имён писателей')),
                ('director', models.CharField(max_length=255, verbose_name='Режисёр')),
                ('actor_names', models.CharField(max_length=255, null=True, verbose_name='Список имён актёров')),
                ('actors', models.ManyToManyField(blank=True, related_name='Movie', to='mainapp.Actor', verbose_name='Актёр')),
                ('writers', models.ManyToManyField(blank=True, related_name='Movie', to='mainapp.Writer', verbose_name='Писатель')),
            ],
        ),
    ]
